POST http://localhost:8080/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHRlcmkiLCJpZCI6IjYzYmRhNjM4MjY5NmEyMzlkYTFiYjgwYiIsImlhdCI6MTY3MzQ1ODE1Nn0.vt0SIbaxr_SWKDKFZF0GivR2EiD7Wqs59fIGcwWnVfg

{
    "title": "100followers special",
    "author": "Miksu",
    "url": "youtube.com",
    "likes": 12,
    "username": "petteri"
}

###
DELETE http://localhost:8080/api/blogs/63befc361334c7c80dbfb215 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBldHRlcmkiLCJpZCI6IjYzYmRhNjM4MjY5NmEyMzlkYTFiYjgwYiIsImlhdCI6MTY3MzQ1ODE1Nn0.vt0SIbaxr_SWKDKFZF0GivR2EiD7Wqs59fIGcwWnVfg

###
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "mikael",
    "name": "Superuser",
    "password": "salainen"
}